name: "Run next to run-ci.yaml"


on: 
  push:
    branches:
      - "release/*"


jobs: 

    list_object:
      name: list_object
      runs-on: ubuntu-latest
      steps:
        - name: CheckCode
          uses: actions/checkout@v2.3.4

        - name: Runls
          run: | 
            echo $pwd
            echo "{{ GITHUB_WORKFLOW}}"
            echo "{{ GITHUB_SHA }}"
            echo "{{ GITHUB_REF }}"
